# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc

build:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  before_script:
     - apt-get update && apt-get -y install make libglfw3-dev libglm-dev cmake
  script:
    - mkdir build
    - cd build && cmake .. && make
  artifacts:
    paths:
      - build/testbed/terrain_test
      - build/testbed/simple_test
      - build/atmosphere_map
      - build/curvature_map
      - shaders
  # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
  # cache:
  #   paths:
  #     - "*.o"

# run tests using the binary built before
#test:
#  stage: test
#  script:
#    - ./runmytests.sh
